# **Linear Algebra**

## ***Vector***

### What is a Vector
>A vector is a tuple of one or more values called `scalars`标量.

Vectors are often represented using a lowercase character such as “v”;

```python
v = (v1, v2, v3)
```
Where v1, v2, v3 are scalar values, often real values.

### Defining a Vector

>We can represent a vector in Python as a `NumPy array`.

A NumPy array can be created from a list of numbers. For example, below we define a vector with the length of 3 and the integer values 1, 2, and 3.

In [1]:
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


### vector multiplication
$ c = a * b $

>As with addition and subtraction, this operation is performed `element-wise` to result in a new vector of the same length.

$ a * b = (a_1 * b_1, a_2 * b_2, a_3 * b_3) $   

In [3]:
# multiply vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


### Vector dot product  `v1.dot(v2)`
>We can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar.

The dot product is the key tool for calculating `vector projections`, `vector decompositions`, and `determining orthogonality`. The name dot product comes from the symbol used to denote it.

$ c = (a_1b_1 + a_2b_2 + a_3b_3) $

In [6]:
import numpy as np
print(
    a + b,
    a - b,
    a / b,
    a.dot(b),
    sep='\n'
)

[2 4 6]
[0 0 0]
[1. 1. 1.]
14


## ***Matrices***

### What is a Matrix?

>A matrix is a ***two-dimensional array of scalars*** with one or more columns and one or more rows.

The notation for a matrix is often an `uppercase letter`, such as A, and entries are referred to by their two-dimensional `subscript`下标 of row (i) and column (j), such as $a_{ij}$.    
For example: $ A = ((a_{11}, a_{12}), (a_{21}, a_{22}), (a_{31}, a_{32})) $

### Defining a Matrix

>We can represent a matrix in Python using a two-dimensional NumPy array.

A NumPy array can be constructed given ***a list of lists***.

In [7]:
# create matrix
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


### Matrix Addition
>Two matrices with the same dimensions can be added together to create a new third matrix.

`C = A + B`

In [8]:
# add matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


### Matrix Dot Product  `A.dot(B)`

Matrix multiplication, also called the matrix dot product, is more complicated than the previous operations and involves a rule, as not all matrices can be multiplied together.

$ C = A * B $

The rule for matrix multiplication is as follows: 
>The number of columns in the first matrix (A) must equal the number of rows in the second matrix (B).

`C(m,k) = A(m,n) * B(n,k)`


In [14]:
# matrix dot product
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
B = array([[1, 2], [3, 4]])
print(B)
C = A.dot(B)  # or use @ operator for dot product, C = A @ B
print(C)
v = array([[6], [9]])
print(A.dot(v))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[24]
 [54]
 [84]]


### Hadamard product 阿达马积
>For two matrices A and B of the same dimension m × n 维度相同, the Hadamard product A ∘ B (or A ⊙ B) is a matrix of the same dimension as the operands, with elements given by    
$(A\circ B)_{ij}=(A\odot B)_{ij}=(A)_{ij}(B)_{ij}$

For matrices of different dimensions (m × n and p × q, where m ≠ p or n ≠ q) the Hadamard product is undefined.

The Hadamard product is also often denoted using the ⊙ or ∘.

## ***Matrix Types and Operations*** 

### ?? Types

$$ Identity Matrix = \begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix} $$
$$ Orthogonal Matrix  $$

### Operations

#### Transpose  `A.T`
>A defined matrix can be transposed, which creates a new matrix with the number of columns and rows flipped.

$ C = A^{T} $

We can transpose a matrix in NumPy by calling the `T` attribute.

In [15]:
# transpose matrix
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


#### ***?? Inversion  `np.linalg.inv(A)`***
>Matrix inversion is a process that finds another matrix that when multiplied with the matrix, results in an `identity matrix`. Given a matrix A, find matrix B, such that $ AB = I^n $ or $ BA = I^n $.

$$ B = A^{-1} $$

The matrix inversion operation is not computed directly, but rather the inverted matrix is
discovered through a numerical operation, where a suite of efficient methods may be used, often involving forms of **`matrix decomposition`矩阵分解**.    
A matrix can be inverted in NumPy using the `inv()` function.

In [1]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([[1.0, 2.0], [3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


#### Trace  `np.tracne(A)`
>A trace of a `square matrix` is the sum of the values on the main diagonal of the matrix (top-left to bottom-right).

In [2]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


#### ***?? Determinant 矩阵行列式  `np.linalg.det(A)`***

The determinant of a `square matrix` is a scalar representation of the volume of the matrix.
    
    　　The determinant describes the relative geometry of the vectors that make up the　rows of the matrix. More specifically, the determinant of a matrix A tells you the　volume of a box with sides given by rows of A.
                                  Page 119, No Bullshit Guide To Linear Algebra, 2017.
                                  
It is denoted by the $det(A)$ notation or $\left|A\right|$ , where A is the matrix on which we are calculating the determinant.
>　　The determinant of a square matrix is calculated from the elements of the matrix. More
technically, ***the determinant is the product of all the `eigenvalues`特征值 of the matrix.***    
　　Eigenvalues are introduced in the lessons on **`matrix factorization`**矩阵因子分解.    
　　The intuition for the determinant is that it describes the way a matrix will scale another matrix when they are multiplied together.    

In NumPy, the determinant of a matrix can be calculated using the `det()` function.

In [3]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


#### ***?? Rank  `np.linalg.matrix_rank(A)`***

>The rank of a matrix is the estimate of the number of ***`linearly independent`$^{[1]}$*** rows or columns in
a matrix.    

The rank of a matrix M is often denoted as the function rank().

$$rank(A)$$

An intuition for rank is to consider it the number of `dimensions spanned`跨纬度 by all of the vectors within a matrix.

In the theory of vector spaces 向量空间, a set of vectors is said to be linearly dependent if at least one of the vectors in the set can be defined as a linear combination of the others; if no vector in the set can be written in this way, then the vectors are said to be linearly independent.

    　　Linear Independent [1]: In linear algebra, the rank of a matrix A is the dimension of the vector space generated (or spanned) by its columns. This corresponds to the maximal number of linearly independent columns of A. This, in turn, is identical to the dimension of the vector space spanned by its rows. 
    　　Rank is thus a measure of the "nondegenerateness" of the system of linear equations and linear transformation encoded by A.
                                                         --- wikipedia

For example, a rank of 0 suggest all vectors span a point, a rank of 1 suggests all vectors span a line, a rank of 2 suggests all vectors span a two-dimensional plane.

>The rank is estimated numerically, often using a ***`matrix decomposition`*** method. A common approach is to use the ***`Singular-Value Decomposition`*** or `SVD` for short.    

NumPy provides the matrix `rank()` function for calculating the rank of an array.

矩阵行是观测，列是变量，线性独立可以看作观测间的独立和变量间的独立。

In [27]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)
ma = array([[1,2,3,4], [3,7,4,7], [1,2,3,4]])
ma1 = array([[1,2,3,4], [3,7,4,7], [2,4,6,8]])
print(
    ma, 'matrix ma rank: {}'.format(matrix_rank(ma)),
    ma1, 'matrix ma1 rank: {}'.format(matrix_rank(ma1)),
    sep='\n')

[1 2 3]
1
[0 0 0 0 0]
0
[[1 2 3 4]
 [3 7 4 7]
 [1 2 3 4]]
matrix ma rank: 2
[[1 2 3 4]
 [3 7 4 7]
 [2 4 6 8]]
matrix ma1 rank: 2


## ***Matrix Factorization/Matrix Decomposition 矩阵因子分解***  

### What is a Matrix Decomposition?

>　　A matrix decomposition is a way of reducing a matrix into its constituent parts.    
　　It is an approach that can simplify more complex matrix operations that can be performed on the decomposed matrix rather than on the original matrix itself.
  
A common analogy for matrix decomposition is the factoring 因式分解 of numbers, such as the factoring of 25 into 5 x 5. For this reason, matrix decomposition is also called matrix factorization. Like factoring real values, there are many ways to decompose a matrix, hence there are a range of different matrix decomposition techniques.

### LU Matrix Decomposition  `scipy.linalg.lu(A)`

>The LU decomposition is for `square matrices` and decomposes a matrix into L and U components.

$$ A = L \cdot U $$

Where A is the square matrix that we wish to decompose, L is the lower triangle matrix, and U is the upper triangle matrix. A variation of this decomposition that is numerically more stable to solve in practice is called the LUP decomposition, or the LU decomposition with ***`partial pivoting`$^{[1]}$***.

$$ A = P \cdot L \cdot U $$

The rows of the parent matrix are re-ordered to simplify the decomposition process and the additional P matrix specifies a way to permute重新排列 the result or return the result to the original order. There are also other variations of the LU.

    　　Partial pivoting [1]:In partial pivoting, the algorithm selects the entry with largest absolute value from the column of the matrix that is currently being considered as the pivot element.
       Partial pivoting is generally sufficient to adequately reduce round-off error. However, for certain systems and algorithms, complete pivoting (or maximal pivoting) may be required for acceptable accuracy. Complete pivoting interchanges交换 both rows and columns in order to use the largest (by absolute value) element in the matrix as the pivot. 
       Complete pivoting is usually not necessary to ensure numerical stability and, due to the additional cost of searching for the maximal element, the improvement in numerical stability that it provides is typically outweighed by its reduced efficiency for all but the smallest matrices. Hence, it is rarely used.
                                                          --- wikipedia 
[wikipedia](https://en.wikipedia.org/wiki/Pivot_element)

In [28]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# LU decomposition
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### ***QR Decomposition  `np.linalg.qr(A)`***

>The QR decomposition is for `m × n` matrices (not limited to square matrices) and decomposes a matrix into Q and R components.

$$ A = Q \cdot R $$

Where A is the matrix that we wish to decompose, Q a matrix with the size `m × m`, and R is an upper triangle matrix with the size `m × n`. The QR decomposition is found using an `iterative numerical method` that can fail for those matrices that cannot be decomposed, or decomposed easily.

The QR decomposition can be implemented in NumPy using the `qr()` function. By default,
the function returns the Q and R matrices with smaller or reduced dimensions that is more economical.     
We can change this to return the expected sizes of m × m for Q and m × n for
R by specifying the mode argument as `‘complete’`, although this is not required for most
applications.

In [29]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


### Cholesky Decomposition  `np.linalg.cholesky(A)`
>The Cholesky decomposition is for ***`square symmetric matrices`*** where all values are greater than zero, so-called `positive definite matrices`.    
For our interests in machine learning, we will focus on the Cholesky decomposition for real-valued matrices and ignore the cases when working with complex numbers.

$$ A = L \cdot L^{T} $$

Where A is the matrix being decomposed, L is the lower triangular matrix and LT is the
transpose of L.

$$ A = U^{T} \cdot U $$

Where U is the upper triangular matrix. 

The Cholesky decomposition is used for solving `linear least squares` for linear regression, as well as simulation and optimization methods.    
When decomposing symmetric matrices, the Cholesky decomposition is nearly twice as efficient as the LU decomposition and should be preferred in these cases.

In [30]:
# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define symmetrical matrix
A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print(A)
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


## ***Eigendecomposition***

>　　The most used type of matrix decomposition is the eigendecomposition that decomposes a matrix into `eigenvectors` and `eigenvalues`.    
　　Matrix decompositions are a useful tool for reducing a matrix to their constituent parts in order to simplify a range of more complex operations.    
　　Eigendecomposition of a matrix is a type of decomposition that involves decomposing a ***`square matrix`*** into ***a set of eigenvectors and eigenvalues***.


### Eigendecomposition of a Matrix
>　　Eigendecomposition of a matrix is a type of decomposition that involves decomposing a `square matrix` into ***a set of eigenvectors and eigenvalues***.    
　　Eigendecomposition is used as an element to simplify the calculation of other more complex matrix operations.

A vector is an eigenvector of a matrix if it satisfies the following equation.

$$ A \cdot v = \lambda \cdot v $$

This is called the eigenvalue equation, where A is the parent square matrix that we are decomposing, `v` is the `eigenvector of the matrix`, and `λ` is the lowercase Greek letter lambda and represents the `eigenvalue scalar`.

A matrix could have one eigenvector and eigenvalue for each dimension of the parent matrix. Not all square matrices can be decomposed into eigenvectors and eigenvalues, and some can only be decomposed in a way that requires complex numbers. The parent matrix can be shown to be a product of the eigenvectors and eigenvalues.

$$ A = Q \cdot \Lambda \cdot Q^T $$

Where `Q` is a `matrix comprised of the eigenvectors`, `Λ` is the uppercase Greek letter lambda and is the `diagonal matrix comprised of the eigenvalues`, and QT is the transpose of the matrix comprised of the eigenvectors.

### Eigenvectors and Eigenvalues

>　　`Eigenvectors` are unit vectors, which means that their length or magnitude is equal to 1.0. They are often referred as right vectors, which simply means a `column vector` (as opposed to a row vector or a left vector).    
　　`Eigenvalues` are `coefficients` applied to eigenvectors that give the vectors their length or magnitude.

### Calculation of Eigendecomposition  `np.linalg.eig()`
An eigendecomposition is calculated on a square matrix using an efficient iterative algorithm. Often an eigenvalue is found first, then an eigenvector is
found to solve the equation as a set of coefficients.     
The eigendecomposition can be calculated in NumPy using the `eig()` function.

In [31]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Confirm an Eigenvector and Eigenvalue
We can confirm that a vector is indeed an eigenvector of a matrix. We do this by multiplying(dot product)
the candidate eigenvector, then by the value vector, finally comparing the two results.    
The example multiplies the original matrix with the first eigenvector and compares it to the
first eigenvector multiplied by the first eigenvalue. 

In [33]:
# confirm eigenvector
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
# factorize
values, vectors = eig(A)
# confirm first eigenvector
print("Comparing A.dot(vectors[:, 0]) and vectors[:, 0] * values[0]")
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

Comparing A.dot(vectors[:, 0]) and vectors[:, 0] * values[0]
[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [37]:
print(A, vectors[:, 0], sep='\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[-0.23197069 -0.52532209 -0.8186735 ]


### Reconstruct Matrix
+ First, the list of eigenvectors must be taken together as a matrix, where each vector becomes a row. The eigenvalues need to be arranged into a diagonal matrix.
+ Next, we need to calculate the inverse of the eigenvector matrix.
+ Finally, these elements need to be multiplied together with the dot() function.

In [38]:
# reconstruct matrix
from numpy import diag
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
# create matrix from eigenvectors
Q = vectors
# create inverse of eigenvectors matrix
R = inv(Q)
# create diagonal matrix from eigenvalues
L = diag(values)
# reconstruct the original matrix
B = Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## ***Singular-Value Decomposition*** 
>Perhaps the most known and widely used matrix decomposition method is the `Singular-Value Decomposition`, or `SVD`. All matrices have an SVD, which makes it more stable than other methods, such as the eigendecomposition. As such, it is often used in a wide array of applications including `compressing`, `denoising`, and `data reduction`. 

### What is the Singular-Value Decomposition
>The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for
reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations
simpler.

$$ A = U \cdot \Sigma \cdot V^T $$

Where `A` is the real `n × m matrix` that we wish to decompose, `U` is an `m × m matrix`, `Σ`
represented by the uppercase Greek letter sigma) is an `m × n diagonal matrix`, and `V^T` is the V
`transpose of an n × n matrix` where T is a superscript. 

The diagonal values in the `Σ matrix` are known as the `singular values` of the original matrix
A. The columns of the `U matrix` are called the `left-singular vectors` of A, and the `columns of V` are called the `right-singular vectors` of A. The SVD is calculated via `iterative numerical
methods`.

The SVD is used widely both in the calculation of other matrix operations, such as `matrix inverse`, but also as a `data reduction` method in machine learning. SVD can also be used in `least squares linear regression`, `image compression`, and `denoising data`.

### Calculate Singular-Value Decomposition  `np.linalg.svd()`

In [42]:
# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### Reconstruct Matrix
The original matrix can be reconstructed from the `U`, `Σ`, and `V^T` elements.    
The `U`, `s`, and `V` elements returned from the svd() cannot be multiplied directly.    
The `s` vector must be converted into a `diagonal matrix` using the diag() function.    

By default, this function will create a square matrix that is m × m, relative to our original matrix. ***This causes a problem as the size of the matrices do not fit the rules of matrix multiplication, where the number of columns in a matrix must match the number of rows in the subsequent matrix.*** After creating the `square Σ diagonal matrix`, the sizes of the matrices are relative to the original n × m matrix that we are decomposing, as follows:

$ U(m × m) · Σ(m × m) · V^T (n × n) $   

Where, in fact, we require:    

$ U(m × m) · Σ(m × n) · V^T (n × n) $

***We can achieve this by creating a new `Σ matrix of all zero values` that is `m × n` (e.g. more rows) and populate the first `n × n` part of the matrix with the `square diagonal matrix` calculated via diag().***

In [43]:
# reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]])
print(A)
# factorize
U, s, V = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)

# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


### Pseudoinverse  `np.linalg.pinv()`
>The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular matrices where the number of rows and columns are not equal. It is also called the Moore-Penrose Inverse 摩尔－彭若斯广义逆/广义逆.

    Matrix inversion is not defined for matrices that are not square. [...] When A has more columns than rows, then solving a linear equation using the pseudoinverse provides one of the many possible solutions.
                                     --- Page 46, Deep Learning, 2016.

The pseudoinverse is denoted as A+, where A is the matrix that is being inverted and + is a superscript. The pseudoinverse is calculated using the singular value decomposition of A:

$$ A^+ = V \cdot D^+ \cdot U^T $$    

Where `A^+` is the `pseudoinvers`e, `D^+` is the `pseudoinverse of the diagonal matrix Σ` and `V^T` is the `transpose of V^T` . We can get U and V from the `SVD operation`.

The `D^+` can be calculated by creating a diagonal matrix from Σ, calculating the `reciprocal of each non-zero element` in `Σ`, and taking the `transpose` if the original matrix was rectangular.

$$ \Sigma = \begin{bmatrix}S_{1,1}&0&0\\0&S_{2,2}&0\\0&0&S_{3,3}\end{bmatrix} $$

$$ D^+ = \begin{bmatrix}\frac{1}{S_{1,1}}&0&0\\0&\frac{1}{S_{2,2}}&0\\0&0&\frac{1}{S_{3,3}}\end{bmatrix} $$

The pseudoinverse provides one way of solving the `linear regression equation`, specifically when there are more rows than there are columns, which is often the case.

In [44]:
# pseudoinverse
from numpy import array
from numpy.linalg import pinv
# define matrix
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


We can calculate the pseudoinverse manually via the SVD and compare the results to the pinv() function.    
+ First we must calculate the SVD.    
+ Next we must calculate the reciprocal of each value in the s array.
+ Then the s array can be transformed into a diagonal matrix with an added row of zeros to make it rectangular.    
+ Finally, we can calculate the pseudoinverse from the elements.

$$ A^+ = V^T \cdot D^T \cdot U^T $$



In [45]:
# pseudoinverse via svd
from numpy import array
from numpy.linalg import svd
from numpy import zeros
from numpy import diag
# define matrix
A = array([
    [0.1, 0.2],
    [0.3, 0.4],
    [0.5, 0.6],
    [0.7, 0.8]])
print(A)
# factorize
U, s, V = svd(A)

# reciprocals of s
d = 1.0 / s

# create m x n D matrix
D = zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)

# calculate pseudoinverse
B = V.T.dot(D.T).dot(U.T)
print(B)

[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  9.07607323e-15  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


### Dimensionality Reduction
>A popular application of SVD is for dimensionality reduction. Data with a large number of
features, such as more features (columns) than observations (rows) may be reduced to a ***smaller subset of features that are most relevant to the prediction problem. The result is a matrix with a lower rank that is said to approximate the original matrix.***    

To do this we can perform an SVD operation on the original data and select the top `k` largest `singular values` in `Σ`. These columns can be selected from Σ and the rows selected from V^T .    
An approximate `B` of the original matirx `A` can then be reconstructed.

$$ B = U \cdot \Sigma_k \cdot V_k^T $$

>In natural language processing, this approach can be used on matrices of word occurrences
or word frequencies in documents and is called `Latent Semantic Analysis` or `Latent Semantic Indexing`. In practice, we can retain and work with a descriptive subset of the data called `T`. This is a dense summary of the matrix or a projection.

$$ T = U \cdot \Sigma_k $$

Further, this transform can be calculated and applied to the original matrix A as well as
other similar matrices.

$$ T = A \cdot V_k^T $$

The example below demonstrates data reduction with the SVD. First a 3 × 10 matrix is
defined, with more columns than rows. The SVD is calculated and only the first two features are selected. The elements are recombined to give an accurate reproduction of the original matrix. Finally the transform is calculated two different ways.

In [47]:
# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]])
print(A)
# factorize
U, s, V = svd(A)

# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)

# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(V))
print(B)

# transform
T = U.dot(Sigma)
print(T)
T = A.dot(V.T)
print(T)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


The `scikit-learn` provides a `TruncatedSVD class` that implements this capability directly. The TruncatedSVD class can be created in which you must specify the number of desirable features or components to select, e.g. 2. Once created, you can fit the transform (e.g. calculate $V_k^T$ ) by calling the fit() function, then apply it to the original matrix by calling the transform() function. The result is the transform of A called T above.

In [48]:
# svd data reduction in scikit-learn
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define matrix
A = array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]])
print(A)
# create transform
svd = TruncatedSVD(n_components=2)
# fit transform
svd.fit(A)
# apply transform
result = svd.transform(A)
print(result)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


# **Statistics**

## Introduction to Multivariate Statistics

### Expected Value and Mean
***`In probability`***, the average value of some random variable X is called the expected value or the expectation.
It is calculated as the `probability weighted sum of values` that can be drawn.

$$ E[x] = \sum x_1p_1, x_2p_2, x_3p_3, \cdots, x_np_n  $$

In simple cases, such as the flipping of a coin or rolling a dice, the probability of each event is just as likely. Therefore, the expected value can be calculated as the sum of all values multiplied by the reciprocal of the number of values.

$$ E[x] = \frac{1}{n} \times \sum x_1, x_2, x_3, \cdots, x_n $$

---

***`In statistics`***, the mean, or more technically the arithmetic mean or sample mean, can be estimated from a sample of examples drawn from the domain. It is confusing because mean, average, and expected value are used interchangeably. In the abstract, the mean is denoted by the lower case Greek letter mu `µ` and is `calculated from the sample of observations`, rather than all possible values.

$$ \mu = \frac{1}{n} \times \sum x_1, x_2, x_3, \cdots, x_n $$
or
$$ \mu = P(x) \times \sum x $$

Where x is the vector of observations and P(x) is the calculated probability for each value.When calculated for a specific variable, such as x, the mean is denoted as a lower case variable name with a line above, called x-bar e.g. $\bar{x}$.

$$ \bar{x} = \frac{1}{n} \times \sum_{i=1}^{n} x_i $$

In [49]:
# matrix means
from numpy import array
from numpy import mean
# define matrix
M = array([
    [1,2,3,4,5,6],
    [1,2,3,4,5,6]])
print(M)
# column means
col_mean = mean(M, axis=0)
print(col_mean)
# row means
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


### Variance and Standard Deviation

`In probability`, covariance is the measure of the joint probability for two random variables. It describes how the two variables change together. It is denoted as the function cov(X; Y ), where X and Y are the two random variables being considered.

>Covariance is calculated as expected value or average of the product of the differences of each random variable from their expected values.
$$ cov(X, Y) = E[(X - E[X]) \times (Y - E[Y])] $$

Assuming the expected values for X and Y have been calculated, the covariance can be calculated as below:

$$ cov(X, Y) = \frac{1}{n} \times \sum_{i=1}^n (x_i - E[X]) \times (y_i - E[Y]) $$

`In statistics`, the sample covariance can be calculated in the same way, although with a bias correction, the same as with the variance.

$$ cov(X, Y) = \frac{1}{n-1} \times \sum_{i=1}^n (x_i - E[X]) \times (y_i - E[Y]) $$

The sign of the covariance can be interpreted as whether the two variables increase together (positive) or decrease together (negative).

numpy has a function for calculating a covariance matrix called cov() that we can use to retrieve the covariance. By default, the `cov()` function will calculate the `unbiased` or `sample covariance` between the provided random variables.

In [50]:
# vector covariance
from numpy import array
from numpy import cov
# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)
# define second covariance
y = array([9,8,7,6,5,4,3,2,1])
print(y)
# calculate covariance
Sigma = cov(x,y)[0,1]
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-7.5


The covariance can be normalized to a score between -1 and 1 to make the magnitude interpretable by dividing it by the standard deviation of X and Y . The result is called the correlation of the variables, also called the `Pearson correlation coefficient`.

$$ r = \frac{cov(X, Y)}{s_X s_Y} $$

Where `r` is the `correlation coefficient` of X and Y , `cov(X, Y)` is the `sample covariance` of X and Y and `s_X` and `s_Y` are the `standard deviations` of X and Y respectively.

As with the results from cov() we can access just the correlation of interest from the [0,1] value from the returned squared matrix.

In [51]:
# vector correlation
from numpy import array
from numpy import corrcoef
# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)
# define second vector
y = array([9,8,7,6,5,4,3,2,1])
print(y)
# calculate correlation
corr = corrcoef(x,y)[0,1]
print(corr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-1.0


### ***?? Covariance Matrix***
>The covariance matrix is a `square` and `symmetric` matrix that describes the covariance between two or more random variables.    

The `diagonal of the covariance matrix` are the `variances` of each of the random variables, as such it is often called the variance-covariance matrix.

The covariance matrix is denoted as the uppercase Greek letter Sigma, e.g. `Σ`. The covariance for each pair of random variables is calculated as.

$$ \Sigma = E[(X - E[X]) \times (Y - E[Y])] \;where:\; \Sigma_{i,j} = cov(X_i, X_j) $$

And X is a matrix where each column represents a random variable. The covariance matrix
provides a useful tool for separating the structured relationships in a matrix of random variables. This can be used to decorrelate variables or applied as a transform to other variables. 

The cov() function can be called with a single 2D array where each `sub-array contains a feature` (e.g. column). ***If this function is called with your data defined in a `normal matrix format (rows then columns)`, then a `transpose` of the matrix will need to be provided to the function in order to correctly calculate the covariance of the columns.***

In [60]:
# covariance matrix
from numpy import array
from numpy import cov
# define matrix of observations
X = array([
    [1, 5, 8],
    [3, 5, 11],
    [2, 4, 9],
    [3, 6, 10],
    [1, 5, 10]])
print(X)
# calculate covariance matrix
Sigma = cov(X.T)
print(Sigma)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]
[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]


In [61]:
X.T

array([[ 1,  3,  2,  3,  1],
       [ 5,  5,  4,  6,  5],
       [ 8, 11,  9, 10, 10]])

## Principal Component Analysis
An important machine learning method for dimensionality reduction is called Principal Component Analysis. 
It is a method that uses simple matrix operations from linear algebra and statistics to ***calculate a projection of the original data into the same number or fewer dimensions.***

### ***?? What is Principal Component Analysis***
>Principal Component Analysis, or PCA for short, is a method for `reducing the dimensionality of data`. It can be thought of as a projection method where ***data with m-columns (features) is projected into a subspace with m or fewer columns, whilst retaining the essence of the original data.***

PCA is an operation applied to a dataset, represented by an n × m matrix A that results in a projection of A which we will call B. Let’s walk through the steps of this operation.

$$ A = \begin{pmatrix} a_{1,1}&a_{1,2} \\ a_{2,1}&a_{2,2} \\ a_{3,1}&a_{3,2} \end{pmatrix} $$

$$ B = PCA(A) $$

1. The first step is to calculate the mean values of each column.

$$ M = mean(A) $$

2. Next, we need to center the values in each column by subtracting the mean column value.

$$ C = A − M $$

3. The next step is to calculate the covariance matrix of the centered matrix C. 
Correlation is a normalized measure of the amount and direction (positive or negative) that two columns change together. Covariance is a generalized and unnormalized version of correlation across multiple columns. A covariance matrix is a calculation of covariance of a given matrix with covariance scores for every column with every other column, including itself.

$$ V = cov(C) $$

4. Finally, we calculate the eigendecomposition of the covariance matrix V . This results in a list of eigenvalues and a list of eigenvectors.

$$ values; vectors = eig(V) $$ 

The eigenvectors represent the directions or components for the reduced subspace of B, whereas the eigenvalues represent the magnitudes for the directions. The eigenvectors can be sorted by the eigenvalues in descending order to provide a ranking of the components or axes of the new subspace for A. If all eigenvalues have a similar value, then we know that the existing representation may already be reasonably compressed or dense and that the projection may offer little. If there are eigenvalues close to zero, they represent components or axes of B that may be discarded. A total of m or less components must be selected to comprise the chosen subspace. Ideally, we would select k eigenvectors, called principal components, that have the k largest eigenvalues.

$$ B = select(values; vectors) $$

Other matrix decomposition methods can be used such as Singular-Value Decomposition, or SVD. As such, generally the values are referred to as singular values and the vectors of the subspace are referred to as principal components. Once chosen, data can be projected into the subspace via matrix multiplication.

$$ P = B^T · A $$

Where A is the original data that we wish to project, BT is the transpose of the chosen principal components and P is the projection of A. This is called the covariance method for calculating the PCA, although there are alternative ways to calculate it.

[***Source - machinelearingmastery***](https://machinelearningmastery.com/linear-algebra-machine-learning-7-day-mini-course/)