## ***Vector***

### What is a Vector
>A vector is a tuple of one or more values called `scalars`标量.

Vectors are often represented using a lowercase character such as “v”;

```python
v = (v1, v2, v3)
```
Where v1, v2, v3 are scalar values, often real values.

### Defining a Vector

>We can represent a vector in Python as a `NumPy array`.

A NumPy array can be created from a list of numbers. For example, below we define a vector with the length of 3 and the integer values 1, 2, and 3.

In [1]:
from numpy import array
v = array([1, 2, 3])
print(v)

[1 2 3]


### vector multiplication
$ c = a * b $

>As with addition and subtraction, this operation is performed `element-wise` to result in a new vector of the same length.

$ a * b = (a_1 * b_1, a_2 * b_2, a_3 * b_3) $   

In [3]:
# multiply vectors
from numpy import array
a = array([1, 2, 3])
print(a)
b = array([1, 2, 3])
print(b)
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


### Vector dot product  `v1.dot(v2)`
>We can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar.

The dot product is the key tool for calculating `vector projections`, `vector decompositions`, and `determining orthogonality`. The name dot product comes from the symbol used to denote it.

$ c = (a_1b_1 + a_2b_2 + a_3b_3) $

In [6]:
import numpy as np
print(
    a + b,
    a - b,
    a / b,
    a.dot(b),
    sep='\n'
)

[2 4 6]
[0 0 0]
[1. 1. 1.]
14


## ***Matrices***

### What is a Matrix?

>A matrix is a ***two-dimensional array of scalars*** with one or more columns and one or more rows.

The notation for a matrix is often an `uppercase letter`, such as A, and entries are referred to by their two-dimensional `subscript`下标 of row (i) and column (j), such as $a_{ij}$.    
For example: $ A = ((a_{11}, a_{12}), (a_{21}, a_{22}), (a_{31}, a_{32})) $

### Defining a Matrix

>We can represent a matrix in Python using a two-dimensional NumPy array.

A NumPy array can be constructed given ***a list of lists***.

In [7]:
# create matrix
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


### Matrix Addition
>Two matrices with the same dimensions can be added together to create a new third matrix.

`C = A + B`

In [8]:
# add matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


### Matrix Dot Product  `A.dot(B)`

Matrix multiplication, also called the matrix dot product, is more complicated than the previous operations and involves a rule, as not all matrices can be multiplied together.

$ C = A * B $

The rule for matrix multiplication is as follows: 
>The number of columns in the first matrix (A) must equal the number of rows in the second matrix (B).

`C(m,k) = A(m,n) * B(n,k)`


In [14]:
# matrix dot product
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
B = array([[1, 2], [3, 4]])
print(B)
C = A.dot(B)  # or use @ operator for dot product, C = A @ B
print(C)
v = array([[6], [9]])
print(A.dot(v))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[24]
 [54]
 [84]]


### Hadamard product 阿达马积
>For two matrices A and B of the same dimension m × n 维度相同, the Hadamard product A ∘ B (or A ⊙ B) is a matrix of the same dimension as the operands, with elements given by    
$(A\circ B)_{ij}=(A\odot B)_{ij}=(A)_{ij}(B)_{ij}$

For matrices of different dimensions (m × n and p × q, where m ≠ p or n ≠ q) the Hadamard product is undefined.

The Hadamard product is also often denoted using the ⊙ or ∘.

## ***Matrix Types and Operations*** 🔥

### ?? Types

$$ Identity Matrix = \begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix} $$
$$ Orthogonal Matrix  $$

### Operations

#### Transpose  `A.T`
>A defined matrix can be transposed, which creates a new matrix with the number of columns and rows flipped.

$ C = A^{T} $

We can transpose a matrix in NumPy by calling the `T` attribute.

In [15]:
# transpose matrix
from numpy import array
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


#### ***?? Inversion  `np.linalg.inv(A)`***
>Matrix inversion is a process that finds another matrix that when multiplied with the matrix, results in an `identity matrix`. Given a matrix A, find matrix B, such that $ AB = I^n $ or $ BA = I^n $.

$$ B = A^{-1} $$

The matrix inversion operation is not computed directly, but rather the inverted matrix is
discovered through a numerical operation, where a suite of efficient methods may be used, often involving forms of **`matrix decomposition`矩阵分解**.    
A matrix can be inverted in NumPy using the `inv()` function.

In [1]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([[1.0, 2.0], [3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


#### Trace  `np.tracne(A)`
>A trace of a `square matrix` is the sum of the values on the main diagonal of the matrix (top-left to bottom-right).

In [2]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


#### ***?? Determinant 矩阵行列式***  `np.linalg.det(A)`

The determinant of a `square matrix` is a scalar representation of the volume of the matrix.
    
    　　The determinant describes the relative geometry of the vectors that make up the　rows of the matrix. More specifically, the determinant of a matrix A tells you the　volume of a box with sides given by rows of A.
                                  Page 119, No Bullshit Guide To Linear Algebra, 2017.
                                  
It is denoted by the $det(A)$ notation or $\left|A\right|$ , where A is the matrix on which we are calculating the determinant.
>　　The determinant of a square matrix is calculated from the elements of the matrix. More
technically, ***the determinant is the product of all the `eigenvalues`特征值 of the matrix.***    
　　Eigenvalues are introduced in the lessons on **`matrix factorization`**矩阵因子分解.    
　　The intuition for the determinant is that it describes the way a matrix will scale another matrix when they are multiplied together.    

In NumPy, the determinant of a matrix can be calculated using the `det()` function.

In [3]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


#### Rank  `np.linalg.matrix_rank(A)`

>The rank of a matrix is the estimate of the number of `linearly independent` rows or columns in
a matrix.    

The rank of a matrix M is often denoted as the function rank().

$$rank(A)$$

An intuition for rank is to consider it the number of `dimensions spanned`跨纬度 by all of the vectors within a matrix.

In the theory of vector spaces 向量空间, a set of vectors is said to be linearly dependent if at least one of the vectors in the set can be defined as a linear combination of the others; if no vector in the set can be written in this way, then the vectors are said to be linearly independent.

    　　In linear algebra, the rank of a matrix A is the dimension of the vector space generated (or spanned) by its columns. This corresponds to the maximal number of linearly independent columns of A. This, in turn, is identical to the dimension of the vector space spanned by its rows. 
    　　Rank is thus a measure of the "nondegenerateness" of the system of linear equations and linear transformation encoded by A.
                                                         --- wikipedia

For example, a rank of 0 suggest all vectors span a point, a rank of 1 suggests all vectors span a line, a rank of 2 suggests all vectors span a two-dimensional plane.

>The rank is estimated numerically, often using a `matrix decomposition` method. A common approach is to use the `Singular-Value Decomposition` or `SVD` for short.    

NumPy provides the matrix `rank()` function for calculating the rank of an array.

矩阵行是观测，列是变量，线性独立可以看作观测间的独立和变量间的独立。

In [11]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)
ma = array([[1,2,3,4], [3,7,4,7], [1,2,3,4]])
print('matrix rank: ', matrix_rank(ma))

[1 2 3]
1
[0 0 0 0 0]
0
matrix rank:  2


## ***Matrix Factorization 矩阵因子分解***  🎁

## ***Singular-Value Decomposition***  🎉🎊

[***Source - machinelearingmastery***](https://machinelearningmastery.com/linear-algebra-machine-learning-7-day-mini-course/)